[build]
    command = "npm run build"
    publish = "public"
[dev]
    command = "npm run develop"
    port = 9000
    publish =  "public"
[context.production.environment]
    NODE_VERSION = "19.1.0"
[functions]
    node_bundler = "esbuild"